# Generated by Django 4.2.5 on 2023-09-13 08:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(editable=False, error_messages={'Size': 'title must not be greater than 200'}, max_length=200)),
                ('description', models.TextField(null=True, unique_for_date='publication_year')),
                ('publication_year', models.IntegerField(blank=True, db_column='book_publication', help_text='Enter the publication year of the Book.')),
                ('publication_date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[website.models.Book.validate_positive])),
                ('book_url', models.URLField(blank=True)),
                ('author_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(upload_to='location', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'pdf'))])),
                ('file', models.FileField(upload_to='location')),
                ('file_path', models.FilePathField()),
                ('user_ip', models.GenericIPAddressField()),
                ('reading_time', models.DurationField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.author')),
            ],
        ),
    ]
