# Generated by Django 4.2.5 on 2023-09-14 07:54

from django.db import migrations,models

def delete_data(apps, schema_editor):
    Book = apps.get_model('website', 'Book')
    records_to_delete = Book.objects.filter(price='5.00')
    records_to_delete.delete()

class Migration(migrations.Migration):



    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_data),
        migrations.AlterField(
            model_name='Book',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
