# Generated by Django 4.2.5 on 2023-09-14 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20230914_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AlterField(
            model_name='book',
            name='added_at',
            field=models.DateTimeField(verbose_name='Added date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.FilePathField(path=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
