# Generated by Django 4.2.5 on 2023-09-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_book_description_alter_book_added_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.book',),
        ),
    ]
