# Generated by Django 4.2.5 on 2023-09-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='group_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('bronze', 'Bronze'), ('silver', 'Silver')], default='gold', max_length=10),
        ),
    ]
