# Generated by Django 4.2.5 on 2023-09-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group_type',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('BRONZE', 'BRONZE'), ('SILVER', 'SILVER')], default='GOLD', max_length=10),
        ),
    ]
