# Generated by Django 4.2.5 on 2023-09-22 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_ip_address_alter_customuser_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ip_address',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
