# Generated by Django 4.2.5 on 2023-09-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_updated_time_alter_customuser_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group_type',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('BRONZE', 'BRONZE'), ('SILVER', 'SILVER')], max_length=10),
        ),
    ]
